# Applied Machine Learning (2022), exercises


## General instructions for all exercises

Follow the instructions and fill in your solution under the line marked by tag

> YOUR CODE HERE

Remove also line 

> raise NotImplementedError()

**Do not change other areas of the document**, since it may disturb the autograding of your results!
  
Having written the answer, execute the code cell by and pressing `Shift-Enter` key combination. The code is run, and it may print some information under the code cell. The focus automatically moves to the next cell and you may "execute" that cell by pressing `Shift-Enter` again, until you have reached the code cell which tests your solution. Execute that and follow the feedback. Usually it either says that the solution seems acceptable, or reports some errors. You can go back to your solution, modify it and repeat everything until you are satisfied. Then proceed to the next task.
   
Repeat the process for all tasks.

The notebook may also contain manually graded answers. Write your manually graded answer under the line marked by tag:

> YOUR ANSWER HERE

Manually graded tasks are text in markdown format. It may contain text, pseudocode, or mathematical formulas. You can write formulas with $\LaTeX$-syntax by enclosing the formula with dollar signs (`$`), for example `$f(x)=2 \pi / \alpha$`, will produce $f(x)=2 \pi / \alpha$

When you have passed the tests in the notebook, and you are ready to submit your solutions, validate and submit your solution using the nbgrader tools from the `Nbgrader/Assignment List`-menu.


# Python warmup

## Create a  python data structures

1. Create an integer scalar variable `x`, and print it
1. Create a python list, `l`, and print it using function `list()` or directly with syntax `l=[1,4,2,3]`
1. Create a [numpy array](https://numpy.org/doc/stable/reference/generated/numpy.array.html), `a`, and print it. Tip: Import numpy library first by using: ```import numpy as np``` 

Python lists are suitable in many cases, but they are not efficient for large amounts of data or mathematical operations. Numpy arrays include a lot of useful functions which are packaged in numpy arrays.

In [1]:
# YOUR CODE HERE
import numpy as np

x=1
print(x)
l=list((1,4,2,3))
print(l)
a=np.array([1,2,3,4])
print(a)

1
[1, 4, 2, 3]
[1 2 3 4]


In [ ]:
if 'x' not in globals():
    print("x not found! Please define x as scalar variable.")
elif 'l' not in globals():
    print("l not found! Please define l list.")
elif 'a' not in globals():
    print("a not found! Please define a as numpy array.")
else:
    print("No errors found this far. Your code may work.")


## Use numpy functions for creating arrays

1. Create a numpy array, `values`, which has 100 consequent values between 0 and $\pi$ using [np.linspace()](https://numpy.org/doc/stable/reference/generated/numpy.linspace.html?highlight=linspace#numpy.linspace). Use ```np.pi``` as constant for $\pi$.
1. Create a two-dimensional array `M` of 5x5 [zeros](https://numpy.org/doc/stable/reference/generated/numpy.zeros.html?highlight=zeros#numpy.zeros) or 5x5 [ones](https://numpy.org/doc/stable/reference/generated/numpy.ones.html?highlight=ones#numpy.ones). using appropriate functions
1. Create one more 2 dimensional array with the following code ```A=np.array([[1,2,3], [4,5,6]])```

**TIP:** to find out what other functions or constants are included in NumPy package, write `np.` in the command line, and press TAB-key to get a list of possible completions, or SHIFT-TAB to get the help window.

In [5]:
# YOUR CODE HERE
import numpy as np
values = np.linspace(1, np.pi)
print(values)

M = np.zeros((5,5))
print(M)

A=np.array([[1,2,3], [4,5,6]])
print(A)

[1.         1.04370597 1.08741195 1.13111792 1.17482389 1.21852986
 1.26223584 1.30594181 1.34964778 1.39335375 1.43705973 1.4807657
 1.52447167 1.56817764 1.61188362 1.65558959 1.69929556 1.74300153
 1.78670751 1.83041348 1.87411945 1.91782542 1.9615314  2.00523737
 2.04894334 2.09264931 2.13635529 2.18006126 2.22376723 2.2674732
 2.31117918 2.35488515 2.39859112 2.44229709 2.48600307 2.52970904
 2.57341501 2.61712098 2.66082696 2.70453293 2.7482389  2.79194487
 2.83565085 2.87935682 2.92306279 2.96676876 3.01047474 3.05418071
 3.09788668 3.14159265]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[1 2 3]
 [4 5 6]]


In [ ]:
errorfound=False
require=('values', 'M', 'A')
for var in require:
    if var not in globals():
        print(var, "not found! Please define it.")
        errorfound=True
if not errorfound:
    print("No errrors found this far, your code may work :)")
        

## Manipulate data structures
1. Study the shape of previously created numpy arrays by using function ```.shape()``` included in the arrays you created.
1. Try to calculate also the sum of all values in those arrays with ```.sum()``` function. Store the sum of array `values` to variable called `s`.
1. Transpose a two dimensional array with function ```.T``` for example ```A.T``` and name the result as `tA`
1. Transposing a one dimensional array looks sadly slightly illogical, because it needs to be also converted to two dimensional at the same time. The row vector `values` can be transposed to column vector with syntax `
values.reshape(-1,1)`. Try it and name the result as `tvalues`. 
1. Try also to transpose the column vector back to row vector


In [24]:
# YOUR CODE HERE
# 1

import numpy as np
values = np.linspace(1, np.pi)
print(values.shape)

M = np.zeros((5,5))
print(M.shape)

A=np.array([[1,2,3], [4,5,6]])
print(A.shape)


# 2
s = values.sum()
print(s) 

# 3

tA = A.T
print(tA)

# 4

tvalues = values.reshape(-1,1)
print(tvalues)

# 5

row = M.flatten()
print(M)
print(row)



(50,)
(5, 5)
(2, 3)
103.53981633974483
[[1 4]
 [2 5]
 [3 6]]
[[1.        ]
 [1.04370597]
 [1.08741195]
 [1.13111792]
 [1.17482389]
 [1.21852986]
 [1.26223584]
 [1.30594181]
 [1.34964778]
 [1.39335375]
 [1.43705973]
 [1.4807657 ]
 [1.52447167]
 [1.56817764]
 [1.61188362]
 [1.65558959]
 [1.69929556]
 [1.74300153]
 [1.78670751]
 [1.83041348]
 [1.87411945]
 [1.91782542]
 [1.9615314 ]
 [2.00523737]
 [2.04894334]
 [2.09264931]
 [2.13635529]
 [2.18006126]
 [2.22376723]
 [2.2674732 ]
 [2.31117918]
 [2.35488515]
 [2.39859112]
 [2.44229709]
 [2.48600307]
 [2.52970904]
 [2.57341501]
 [2.61712098]
 [2.66082696]
 [2.70453293]
 [2.7482389 ]
 [2.79194487]
 [2.83565085]
 [2.87935682]
 [2.92306279]
 [2.96676876]
 [3.01047474]
 [3.05418071]
 [3.09788668]
 [3.14159265]]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0.]


In [ ]:
errorfound=False
require=('s', 'tA', 'tvalues')
for var in require:
    if var not in globals():
        print(var, "not found! Please define it.")
        errorfound=True
if not errorfound:
    print("No errrors found this far, your code may work :)")
         

## Loops and functions
1. Create a function `squares`, which takes a an integer, n, as a parameter, and prints the values and squares of n first integers, and returns the square of n as its value.

The functions in Python are created with the keyword `def`, like `def sum(x):`. The semicolon starts the block, which is included in the body of the function. All lines included in the function body needs to be indented. No begin-end or curly braces needed to indicate a block, like in many other languages.

The for loop for 1 to 10 can be programmed using `range()`-function, which returns an iterable range of values, The for-loop interates through each of the values using the following syntax: `for i in range(10):`. The colon starts the block included in the loop body, which is expressed with intendations. 

The function can return with value using the `return` keyword.

Test your function.

You can also test the `range()` function to see how it works. 

See more instructions and examples from [W3C Python school material](https://www.w3schools.com/python/python_functions.asp)


In [45]:
# YOUR CODE HERE
def squares(n):
    for i in range(1, n + 1):
         print(f"The value is {i} and its square is {i ** 2}")
    return i ** 2

n = 5
result = squares(n)
print(f"The square of {n} is {result}")

print("Testing range(5):")
for i in range(5):  
    print(i)

   

The value is 1 and its square is 1
The value is 2 and its square is 4
The value is 3 and its square is 9
The value is 4 and its square is 16
The value is 5 and its square is 25
The square of 5 is 25
Testing range(5):
0
1
2
3
4


In [ ]:
errorfound=False
Ncorrect=0
require=['squares']
for var in require:
    if var not in globals():
        print(var, "not found! Please define it.")
        errorfound=True
if not errorfound:
    Ncorrect+=1
if squares(4)==16:
    Ncorrect+=1
else:
    errorfound=True
    print("The function squares did not return the correct value")
if not errorfound:
    print("No errrors found this far, your code may work :)")
         

# Language features

Do you know the answer to the following questions? (No points offered, though)

1. Is Python an object oriented language?
1. Is Python interpreted or compiled language?
1. Is Python fast to run?

## Summary
1. NumPy arrays are very important data structures in Python for machine learning and mathematical operations
1. Numpy arrays can be 1 dimensional or many dimensional
1. Two dimensional arrays can be transposed like matrices in mathematics 
1. Numpy arrays contain a large amount of functions which can be applied to their content
2. Functions are defined with `def f(x):` syntax. They are important in capsulating parts of the task behind one abstract name.
3. Loops are made by iterating through and iterable object, such as list of values, array or range()
4. The code blocks in Python are indicated using intendation, noth with curly braces or begin-end constructions, like in many other languages.